services:

  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - NAVER_REDIRECT_URI=${NAVER_REDIRECT_URI}
      - NAVER_AUTHORIZATION_URI=${NAVER_AUTHORIZATION_URI}
      - NAVER_TOKEN_URI=${NAVER_TOKEN_URI}
      - NAVER_USER_INFO_URI=${NAVER_USER_INFO_URI}
      - PROJECT_PATH=${PROJECT_PATH}
      - SPRING_DATASOURCE_URL=${DB_DATASOURCE}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT}
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - ELASTIC_SEARCH_HOST=${ELASTIC_SEARCH_HOST}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
      - mysql
      - es1
      - es2
      - es3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: cafedb
    volumes:
      - mysql_data:/var/lib/mysql

  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: es1
    environment:
      - node.name=es-node-1
      - cluster.name=search-cluster
      #      - discovery.type=single-node
      - discovery.seed_hosts=es1,es2,es3
      - cluster.initial_master_nodes=es-node-1,es-node-2,es-node-3
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es1_data:/usr/share/elasticsearch/data

  es2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: es2
    environment:
      - node.name=es-node-2
      - cluster.name=search-cluster
      #      - discovery.type=single-node
      - discovery.seed_hosts=es1,es2,es3
      - cluster.initial_master_nodes=es-node-1,es-node-2,es-node-3
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - network.host=0.0.0.0
    ports:
      - "9201:9200"
      - "9301:9300"
    volumes:
      - es2_data:/usr/share/elasticsearch/data

  es3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: es3
    environment:
      - node.name=es-node-3
      - cluster.name=search-cluster
      #      - discovery.type=single-node
      - discovery.seed_hosts=es1,es2,es3
      - cluster.initial_master_nodes=es-node-1,es-node-2,es-node-3
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - network.host=0.0.0.0

    ports:
      - "9202:9200"
      - "9302:9300"
    volumes:
      - es3_data:/usr/share/elasticsearch/data



volumes:
  mysql_data:
  es1_data:
  es2_data:
  es3_data:
